import { defineConfig } from "vite-plus";

const restrictEnvAccess = {
  "no-restricted-properties": [
    "error",
    {
      object: "process",
      property: "env",
      message:
        "Use `import { env } from '~/env'` instead to ensure validated types.",
    },
  ],
  "no-restricted-imports": [
    "error",
    {
      name: "process",
      importNames: ["env"],
      message:
        "Use `import { env } from '~/env'` instead to ensure validated types.",
    },
  ],
} as const;

export default defineConfig({
  lint: {
    // Only the rules below run: the ones the old ESLint config enabled
    // (eslint recommended, typescript-eslint recommended + type-checked +
    // stylistic, React and React Hooks recommended).
    plugins: ["typescript", "import"],
    categories: { correctness: "off" },
    options: {
      typeAware: true,
      reportUnusedDisableDirectives: "warn",
    },
    ignorePatterns: [
      "**/*.config.*",
      "packages/auth/script/**",
      // Legacy Plop generator: never linted, and it has no tsconfig.
      "turbo/**",
    ],
    rules: {
      "for-direction": "error",
      "no-array-constructor": "error",
      "no-async-promise-executor": "error",
      "no-case-declarations": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": "error",
      "no-constant-binary-expression": "error",
      "no-constant-condition": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-dupe-else-if": "error",
      "no-duplicate-case": "error",
      "no-empty": "error",
      "no-empty-character-class": "error",
      "no-empty-function": "error",
      "no-empty-pattern": "error",
      "no-empty-static-block": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-fallthrough": "error",
      "no-global-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-prototype-builtins": "error",
      "no-regex-spaces": "error",
      "no-self-assign": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-unexpected-multiline": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-expressions": "error",
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "no-useless-backreference": "error",
      "no-useless-catch": "error",
      "no-useless-escape": "error",
      "no-var": "error",
      "prefer-const": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "require-yield": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
      "typescript/adjacent-overload-signatures": "error",
      "typescript/array-type": "error",
      "typescript/await-thenable": "error",
      "typescript/ban-ts-comment": "error",
      "typescript/ban-tslint-comment": "error",
      "typescript/class-literal-property-style": "error",
      "typescript/consistent-generic-constructors": "error",
      "typescript/consistent-indexed-object-style": "error",
      "typescript/consistent-type-assertions": "error",
      "typescript/consistent-type-definitions": "error",
      "typescript/consistent-type-imports": [
        "warn",
        { prefer: "type-imports", fixStyle: "separate-type-imports" },
      ],
      "typescript/dot-notation": "error",
      "typescript/no-array-delete": "error",
      "typescript/no-base-to-string": "error",
      "typescript/no-confusing-non-null-assertion": "error",
      "typescript/no-duplicate-enum-values": "error",
      "typescript/no-duplicate-type-constituents": "error",
      "typescript/no-empty-object-type": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-extra-non-null-assertion": "error",
      "typescript/no-floating-promises": "error",
      "typescript/no-for-in-array": "error",
      "typescript/no-implied-eval": "error",
      "typescript/no-inferrable-types": "error",
      "typescript/no-misused-new": "error",
      "typescript/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } },
      ],
      "typescript/no-namespace": "error",
      "typescript/no-non-null-asserted-optional-chain": "error",
      "typescript/no-non-null-assertion": "error",
      "typescript/no-redundant-type-constituents": "error",
      "typescript/no-require-imports": "error",
      "typescript/no-this-alias": "error",
      "typescript/no-unnecessary-type-assertion": "error",
      "typescript/no-unnecessary-type-constraint": "error",
      "typescript/no-unsafe-argument": "error",
      "typescript/no-unsafe-assignment": "error",
      "typescript/no-unsafe-call": "error",
      "typescript/no-unsafe-declaration-merging": "error",
      "typescript/no-unsafe-enum-comparison": "error",
      "typescript/no-unsafe-function-type": "error",
      "typescript/no-unsafe-member-access": "error",
      "typescript/no-unsafe-return": "error",
      "typescript/no-unsafe-unary-minus": "error",
      "typescript/no-wrapper-object-types": "error",
      "typescript/non-nullable-type-assertion-style": "error",
      "typescript/only-throw-error": "error",
      "typescript/prefer-as-const": "error",
      "typescript/prefer-find": "error",
      "typescript/prefer-for-of": "error",
      "typescript/prefer-function-type": "error",
      "typescript/prefer-includes": "error",
      "typescript/prefer-namespace-keyword": "error",
      "typescript/prefer-nullish-coalescing": "error",
      "typescript/prefer-promise-reject-errors": "error",
      "typescript/prefer-regexp-exec": "error",
      "typescript/prefer-string-starts-ends-with": "error",
      "typescript/require-await": "error",
      "typescript/restrict-plus-operands": "error",
      "typescript/restrict-template-expressions": "error",
      "typescript/triple-slash-reference": "error",
      "typescript/unbound-method": "error",
    },
    overrides: [
      {
        // eslint recommended rules that typescript-eslint turns off for TS
        // files, because the compiler already reports these.
        files: ["**/*.js"],
        rules: {
          "constructor-super": "error",
          "getter-return": "error",
          "no-class-assign": "error",
          "no-const-assign": "error",
          "no-dupe-class-members": "error",
          "no-dupe-keys": "error",
          "no-func-assign": "error",
          "no-import-assign": "error",
          "no-new-native-nonconstructor": "error",
          "no-obj-calls": "error",
          "no-redeclare": "error",
          "no-setter-return": "error",
          "no-this-before-super": "error",
          "no-unreachable": "error",
          "no-unsafe-negation": "error",
          "no-with": "error",
        },
      },
      {
        // Web app, mobile app and UI package.
        files: ["apps/**", "packages/ui/**"],
        plugins: ["react"],
        rules: {
          "react/display-name": "error",
          "react/jsx-key": "error",
          "react/jsx-no-comment-textnodes": "error",
          "react/jsx-no-duplicate-props": "error",
          "react/jsx-no-target-blank": "error",
          "react/jsx-no-undef": "error",
          "react/no-children-prop": "error",
          "react/no-danger-with-children": "error",
          "react/no-direct-mutation-state": "error",
          "react/no-find-dom-node": "error",
          "react/no-is-mounted": "error",
          "react/no-render-return-value": "error",
          "react/no-string-refs": "error",
          "react/no-unescaped-entities": "error",
          "react/no-unknown-property": "error",
          // React Hooks
          "react/error-boundaries": "error",
          "react/exhaustive-deps": "warn",
          "react/globals": "error",
          "react/immutability": "error",
          "react/incompatible-library": "warn",
          "react/preserve-manual-memoization": "error",
          "react/purity": "error",
          "react/refs": "error",
          "react/rules-of-hooks": "error",
          "react/set-state-in-effect": "error",
          "react/set-state-in-render": "error",
          "react/static-components": "error",
          "react/unsupported-syntax": "warn",
          "react/use-memo": "error",
          "react/void-use-memo": "error",
        },
      },
      {
        // Packages that validate env with t3-env must read it through `env`.
        files: ["apps/tanstack-start/**", "packages/auth/**"],
        rules: restrictEnvAccess,
      },
      {
        files: ["**/env.ts"],
        rules: {
          "no-restricted-properties": "off",
          "no-restricted-imports": "off",
        },
      },
    ],
  },
});
